smu-nity/SMUNITY

- accounts/views.py
- templates/accounts/login.html
- templates/footer.html
- templates/navbar.html
> feat: join & login

- accounts/models.py
> feat: 사용자 정보 테이블 생성 (#10)

- accounts/forms.py
- accounts/views.py
- templates/accounts/register.html
> feat: 이캠퍼스 인증 및 회원가입 (#12)

- accounts/views.py
- config/settings.py
- config/urls.py
- core/admin.py
- core/apps.py
- core/models.py
- core/tests.py
- core/urls.py
- core/views.py
> feat: core 앱 생성 (#14)

- accounts/urls.py
- accounts/views.py
- config/urls.py
- core/urls.py
- core/views.py
- templates/accounts/changePW.html
- templates/core/custom.html
- templates/core/head.html
- templates/core/mypage.html
- templates/navbar.html
> Feat issue 25

- core/views.py
- graduations/models.py
- templates/core/mypage.html
> feat: 마이페이지 (#24)

- core/urls.py
- core/views.py
- templates/core/custom.html
> feat: 삭제기능 확인부탁(#23)

- core/urls.py
- core/views.py
- templates/core/mypage.html
> feat: 기이수과목 엑셀 업로드 (#38)

- core/views.py
- templates/core/mypage.html
> feat: 기이수과목 리스트 필드 수정 (#46)

- core/views.py
> feat: 전공과목 추천 (#55)

- accounts/models.py
- core/views.py
- templates/core/result.html
> feat: 컴퓨터과학과 전공 과목 추천 (#68)

- accounts/models.py
- core/admin.py
- core/views.py
- templates/core/result.html
> Feat issue 67

- accounts/urls.py
- accounts/views.py
- templates/core/mypage.html
> Feat issue 73

- accounts/forms.py
- accounts/views.py
- templates/accounts/register.html
> Fix issue 75

- accounts/urls.py
- accounts/views.py
- templates/accounts/changePW.html
- templates/accounts/login.html
> Feat issue 56

- config/settings.py
> fix: CSRF 토큰 에러 (#83)

- core/views.py
- templates/core/mypage.html
> Fix issue 92

- accounts/admin.py
- accounts/models.py
- accounts/views.py
- static/css/mypage.css
- templates/core/mypage.html
- templates/navbar.html
> Feat issue 96

- templates/base.html
> chore: 오픈 그래프 태그 추가 (#99)

- graduations/models.py
- templates/navbar.html
> Chore issue 99

- graduations/models.py
> fix: dept 최대 길이 (#99)

- templates/accounts/agree.html
> fix: 이용약관 동의 (#103)

- templates/base.html
- templates/navbar.html
> feat: 로그아웃 메시지 (#104)

- accounts/views.py
> feat: 로그인 기록 (#108)

- templates/core/mypage.html
> fix: 마이페이지 학번 수정 (#113)

- accounts/views.py
> fix: 융합전자공학전공 회원가입 에러 (#115)

- README.md
> docs: README 업데이트 (#119)

- README.md
> docs: README 파일 업데이트 (#128)

- accounts/models.py
- graduations/update.py
- templates/core/mypage.html
> fix: 학과 및 전공 업데이트 스크립트 (#134)

- config/settings.py
> fix: 한국 시간으로 변경 (#138)

- core/views.py
- templates/core/mypage.html
> feat: har 파일 업로드 (#132)

- graduations/models.py
> fix: DB 마이그레이션 오류 (#140)

- core/views.py
- static/css/head.css
- templates/core/head.html
- version.md
> feat: 업데이트 내용 모달 (#143)

- templates/core/head.html
> fix: 버튼 에러 (#143)

- templates/core/mypage.html
> design: 모달 마진 수정 (#148)

- config/settings.py
- core/views.py
> chore: 장고 로그 설정 (#150)

- version.md
> version: 1.0.3

- deploy.sh
> chore: 배포 스크립트

- core/views.py
- templates/core/head.html
- version.md
> feat: 사용자 통계 (#152)

- core/views.py
> fix: 파일 업로드 에러 (#156)

- templates/core/head.html
- templates/core/info.html
- templates/core/mypage.html
> version: 1.0.4 (#156)

- accounts/urls.py
- accounts/views.py
- config/settings.py
- templates/core/mypage.html
> Fix issue 117

- templates/base.html
> chore: 네이버 검색 태그 (#163)

- config/urls.py
- templates/robots.txt
> chore: robots.txt 설정 (#163)

- templates/base.html
> Chore issue 163

- templates/base.html
> chore: 네이버 검색 favicon (#163)

- accounts/admin.py
- graduations/admin.py
> Chore issue 170

- deploy.sh
- docker-compose.local.yml
- docker-compose.yml
- requirements.txt
> Chore issue 172

- templates/accounts/login.html
> design: 모달 수정 (#172)

- accounts/views.py
- templates/base.html
- templates/core/head.html
- version.md
> Fix issue 175

- accounts/admin.py
- accounts/models.py
- accounts/views.py
- core/views.py
> feat: Statistics 테이블 추가 (#177)

- static/css/login.css
- templates/accounts/login.html
- templates/core/head.html
- version.md
> design: 로그인 페이지 화면 수정 (#179)

- graduations/update.py
> feat: 업데이트 스크립트 수정 (#181)

- nginx/nginx/nginx.conf
> nginx max_body_size #feat_issue_184

- graduations/update.py
> feat: 경영학부&글경 전공 과목 추가 (#164)

- graduations/update.py
> fix: update 스크립트 오류 (#164)

- graduations/update.py
- templates/accounts/agree.html
- templates/core/head.html
- version.md
> Fix issue 181

- templates/accounts/agree.html
- templates/core/head.html
> feat: 검사대상표 모달 수정 (#182)

- templates/core/mypage.html
> feat: 교육과정 추가 (#182)

- accounts/views.py
- templates/core/head.html
> Fix issue 201

- version.md
> chore: 버전 기록 수정 (#201)

- graduations/update.py
> fix: 데이터 업데이트 스크립트 절대경로로 수정 (#205)

- graduations/update.py
- templates/core/head.html
- version.md
> fix: 데이터 업데이트 스크립트 수정 (#205)

- accounts/urls.py
- accounts/views.py
- static/css/style.css
- templates/accounts/terms.html
- templates/core/head.html
- templates/footer.html
- version.md
> Docs issue 209

- accounts/views.py
> Fix issue 212

- petitions/admin.py
- petitions/models.py
- qna/admin.py
- qna/models.py
> fix: 청원 앱 추가 (#211)

- accounts/models.py
> Chore issue 215

- accounts/views.py
- templates/navbar.html
> chore: 관리자 계정 navbar 수정 (#217)

- accounts/models.py
> feat: 청원 사이트 LoginHistory 테이블 추가 (#222)

- accounts/admin.py
- core/admin.py
- graduations/admin.py
> Feat issue 221

- accounts/admin.py
- core/admin.py
- graduations/admin.py
> feat: 관리자 페이지 수정 (#226)

- .gitignore
- core/views.py
- static/js/head.js
- templates/core/head.html
- version.md
> Fix issue 228

- LICENSE
- README.md
- version.md
> Docs issue 232

- README.md
- version.md
> Docs issue 236

- README.md
> docs: README.md 수정 (#238)

- README.md
- requirements.txt
> Chore issue 289

- core/views.py
- templates/core/mypage.html
> Feat issue 245

- README.md
> version: 1.3.0 (#245)

- static/css/main.css
- templates/core/head.html
> Feat issue 249

- static/css/main.css
- templates/core/mypage.html
> Feat issue 256

- config/settings.py
> fix: ALLOWED_HOSTS 타입 오류 (#265)

- README.md
- config/settings.py
> Fix issue 265

- requirements.txt
> chore: markdown 의존성 추가 (#264)

- README.md
> version: 1.5.0 (#279)

- README.md
- static/css/style.css
- static/rest_framework/css/bootstrap-tweaks.css
- templates/base.html
- templates/qna/question_detail.html
- templates/qna/question_form.html
+ #282 
+ 글자 크기 변경 (반응형)
+ 청원내용 -> 질문내용으로 변경
> feat: 질문 게시판 수정 (#282)

- core/views.py
> fix: 기초교양 검사 오류 (#290)

- README.md
> version: 1.5.5 (#290)

- templates/core/result.html
> fix: 모달 스크롤 오류 (#296)

- accounts/models.py
- templates/core/result.html
> feat: 융합경영학과 졸업요건 수정 (#298)

- core/views.py
- templates/qna/answer_form.html
+ #301
+ 기이수과목 업데이트 시 포맷 오류 해결
> [BUG] 기이수과목 업데이트 시 포맷 오류 (#301)

- README.md
> version: 1.6.2 (#301)

- README.md
- api/views.py
- requirements.txt
> [FEATURE] 재학생 인증 API 수정 (#305)

- README.md
- requirements.txt
> feat: sangmyung-univ-auth 라이브러리 업데이트 (#307)

- LICENSE
- README.md
- requirements.txt
+ #307 
+ v1.2.1 -> v1.2.2
+ LICENSE 수정
> [FEATURE] sangmyung-univ-auth 라이브러리 업데이트 (#307)

- config/urls.py
- core/views.py
- static/js/chart.js
- templates/core/statistics.html
> [FEATURE] 서비스 통계

- config/context_processors.py
- config/settings.py
- templates/footer.html
> [FEATURE] 서비스 버전 표기
